name: Clean Crisp Code
tagline: write code you like
paginate:     1

# Site settings
title: Clean Crisp Code
tag_text: Clean Crisp Code
description: Taylor Franklin - write code you like
url: "http://taylorfranklin.me"
# url: "http://127.0.0.1:4000"
baseurl: ""
twitter_username: tfrank64
font-awesome-include: true # make this false if you don't need font-awesome

# About/contact
author:
  name:       Taylor Franklin
  url:        http://taylorfranklin.me/about 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

